---
name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ghcr.io with docker
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u shoogland --password-stdin

      - name: Build docker image
        run: |
          docker build . --tag "ghcr.io/shoogland/eijkelpower-nl:$GITHUB_SHA" --tag "ghcr.io/shoogland/eijkelpower-nl:latest"

      - name: Push to GitHub Packages with latest tag
        run: docker push ghcr.io/shoogland/eijkelpower-nl:latest

      - name: Push to GitHub Packages with sha tag
        run: docker push "ghcr.io/shoogland/eijkelpower-nl:$GITHUB_SHA"

      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: get kubectl creds
      #   run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 sh-cluster-01

      # - name: get shoost deployment
      #   run: kubectl get deployment -n traefik-system www-shoogland -o yaml > deployment.yaml

      # - name: update image tag
      #   run: sed 's|ghcr\.io\/shoogland\/eijkelpower-nl:.*|ghcr\.io\/shoogland\/eijkelpower-nl:'${GITHUB_SHA}'|' < deployment.yaml > deployment2.yaml

      # - name: apply updated image
      #   run: kubectl apply -f deployment2.yaml
